### PR TITLE
Pointless change to run CI

### PR DESCRIPTION
**Pull request by jeromekelleher**
Trying to debug/reproduce #334

### CODE REVIEW

**Comment by jeromekelleher** [comment]
@bhaller @petrelharp could someone approve my workflow runs please?

**Comment by bhaller** [comment]
> @bhaller @petrelharp could someone approve my workflow runs please?

Done.  Sorry, I was out having lunch.  I think I can give you permissions so you don't need approval any more; I'll poke around in the GH settings.

**Comment by bhaller** [comment]
Oh, I see you're working off of `master`.  You want to be working off of the `multispecies` branch, I think; that is SLiM 4 beta, and that's where the problems have been happening.  I have no idea whether `master` will exhibit the issue or not, it hasn't been touched in quite a while.

**Comment by petrelharp** [comment]
Yep; you'll want to start with https://github.com/MesserLab/SLiM/pull/338 really - I did see the bug there.

**Comment by jeromekelleher** [comment]
Looks like this has been tracked down, so closing.

**Pull request closed without merging**
