### PR TITLE
CMakeLists.txt update for Qt build on linux

### PR DESCRIPTION
**Pull request by brnorris03**
Incorporates changes based on the discussion in PR #49, but ensures that only the CMakeLists.txt changes are included in this PR.

### CODE REVIEW

**Comment by bhaller** [comment]
Thanks Boyana.  I'll add QtSLiM to my travis-ci testing to see how this goes!  :->

**Comment by bhaller** [comment]
Hi @brnorris03 .  I'm trying to get QtSLiM to build on Travis CI using your cmake stuff.  I think it's most of the way there; I cobbled together a .travis.yaml file for the qtslim branch from stuff I found on the internet (to install Qt5 in travis prior to building), and I removed the GLUT dependency in the cmake (which I think is not needed?), and the build gets pretty far before it fails.  But then it fails for a weird reason:

```
In file included from /home/travis/build/MesserLab/SLiM/QtSLiM/QtSLiMWindow_glue.cpp:2:
680/home/travis/build/MesserLab/Release/qtslim_autogen/include/ui_QtSLiMWindow.h:31:10: fatal error: QtSLiMChromosomeWidget.h: No such file or directory
681 #include "QtSLiMChromosomeWidget.h"
682          ^~~~~~~~~~~~~~~~~~~~~~~~~~
683compilation terminated.
```

You can see this at https://api.travis-ci.org/v3/job/566238167/log.txt for the raw log, or https://travis-ci.org/MesserLab/SLiM/builds/566238165 for the processed log.  Perhaps it's just missing a necessary directory in the include paths, but then I'm surprised it would have built on your end.  Any ideas?  (QtSLiMChromosomeWidget.h certainly exists, is added to the branch on GitHub, etc., and the current contents of the branch build fine under Qt Creator for me.)

**Comment by brnorris03** [comment]
@bhaller Can you build with "make VERBOSE=1" so that the log shows the exact compiler commands? Also, the build is being done in a different directory from the source, correct? It would help to see the cmake command, too. Thanks!

**Comment by bhaller** [comment]
> @bhaller Can you build with "make VERBOSE=1" so that the log shows the exact compiler commands?

@brnorris03 I think I have just committed that change.

**Comment by bhaller** [comment]
@brnorris03 Here's the build, which just errored out: https://travis-ci.org/MesserLab/SLiM/builds/566742162

**Comment by bhaller** [comment]
@brnorris03 I'm happy to make you a collaborator (is that the right term? make it so you can commit) if doing this through pull requests and such is proving to be a pain in the neck.  :->

**Comment by brnorris03** [comment]
I can certainly be a collaborator, although figuring out the best PR process is something I'm pretty interested in, as well. I did create a new PR for this tiny change, the CI tests are running now.

**Comment by bhaller** [comment]
Commenting on the new PR.

**Pull request merged**
