### PR TITLE
update tskit (including bigtables code)

### LINKED ISSUE #206: merge latest tskit
Ben Jeffery says: "https://github.com/tskit-dev/tskit/releases/tag/C_0.99.14 is released! I'd love to get some testing here of the new large 64bit columns."  I guess it's time to merge the latest tskit into SLiM.  Want to do a PR, @petrelharp?  Once that's done, I can dig up the test case that triggered the metadata overflow and give it a whirl.  :->

### PR DESCRIPTION
**Pull request by petrelharp**
Closes #206.  But, this hasn't changed anything, I don't think - IIUC, we need to define `_TSK_BIG_TABLES` to turn on bigtableness - see the new note at the top of `treerec/tskit/core.h`.

### CODE REVIEW

**Comment by benjeffery** [comment]
The initial problem was with large ragged columns, which by default are now 64bit and for which you need no new defines.

`_TSK_BIG_TABLES` allows tables to have more than 2^31 rows, which is a separate, experimental, unsupported feature.

**Comment by bhaller** [comment]
Groovy, I'll do a before/after test on this soon.  Thanks to both of you.

**Comment by petrelharp** [comment]
Oh, right! So, this should already fix that previous problem!!!

**Comment by benjeffery** [comment]
Thanks for the quick work here guys!

**Pull request merged**
