### PR TITLE
Add Laplace distribution of fitness effects

### PR DESCRIPTION
**Pull request by nobrien97**
I've been reading about the distributions of mutational effects and one that crops up fairly often is the double exponential (Laplace) (e.g. https://doi.org/10.1534/genetics.116.199190, https://doi.org/10.1371/journal.pgen.1002378, https://doi.org/10.1073/pnas.1902823116). I thought it might be a nice option to have in SLiM natively. Since GSL already has an implementation, I just added that to the repo. I haven't added/updated documentation -- happy to do that if you wanted, but was unsure about how you're handling the docs: are you editing the html or rtf files directly? Or do you have another system to build them? In the meantime, you can test it out with ```initializeMutationType("m1", 0.5, "la", 0.0, 1.0);```

### CODE REVIEW

**Comment by bhaller** [comment]
Hi @nobrien97!  Thanks for the contribution!  Updating the docs is complicated and can only be done by me, at present; so I can handle that.  I've got some pretty extensive diffs in the `smooth` branch that will probably conflict with this, so I might re-implement your diffs rather than deal with resolving the conflicts (a process that I pretty much always screw up, so I avoid it when possible), but that won't be a problem.  (If it matters to you to have diffs authored by you in the SLiM repo, I can notify you once `smooth` is merged and then you can resolve the merge conflicts in this PR prior to merging?)  I guess you used `"la"` to avoid a conflict with the `"l"` linear interaction function type?  That does seem best, although I don't really like moving away from single-letter symbols for all of these.  Hmm.

@petrelharp any comments on this before I move forward with it?

**Comment by nobrien97** [comment]
Hi @bhaller! No worries, I'm happy to resolve conflicts when you've merged ```smooth```. You're right about why I chose "la": I was also considering "d" for double exponential, but it seemed a bit less clear to me... let me know your thoughts.

**Comment by petrelharp** [comment]
(Just popping in here to say that if you're interested in adding some of these DFEs to [stdpopsim](https://github.com/popsim-consortium/stdpopsim) we don't have any double-exponential examples there yet!)

**Comment by bhaller** [comment]
OK, `smooth` has been merged so this is queued up.  I'll clean up (a) the doc, and (b) the Xcode project, after merging this in, for simplicity.  I think I would like to stick to one-letter symbols for these distributions, somewhat arbitrarily; I guess I'm leaning towards `"p"` for this.  I can make this change, or you can @nobrien97.

@petrelharp I guess what I was mostly wondering was: do you think we need this Laplace distribution anywhere else?  As an eidos function, `rlaplace()` or something?  As an interaction kernel, or a spatial kernel for other spatial uses?  This PR covers its addition only as a mutation type DFE.  I'm fine with that – less work is good – but I'm just checking.

**Comment by nobrien97** [comment]
Hi Ben,
I've merged your recent changes into this branch (sorry if you were spammed with emails earlier - I messed up the merge the first time) and changed the Laplace symbol to ```"p"```.

**Comment by bhaller** [comment]
Thanks @nobrien97, will merge soon, when I have time to deal with the related fallout.  Presently on vacation.  :->

**Comment by bhaller** [comment]
This PR now touches 72 files; it appears to contain all of the changes made by me in the `smooth` branch.  I've never really understood why Git does this, but I hate it – I don't want to merge a PR that appears to contains all of those changes all over again, even if it works (which I am suspicious of).  Sigh; not a fan of Git sometimes.  I guess this PR maybe needs to be rebased or something?  I think I'm just going to recreate the necessary changes by hand on my end, but @nobrien97 if you know a better way then feel free.  Maybe someday I will better understand Git's workflow.

**Comment by bhaller** [comment]
OK, here's the final commit used in place of this PR:

https://github.com/MesserLab/SLiM/commit/0800cc31b0c4e15bdcaa83efe522678dcf0534e1

I'm going to close this PR now.  @nobrien97 you're credited for this in the VERSIONS file, and in the credits in the manual.  :->  Thanks for the contribution!

**Comment by petrelharp** [comment]
You're right - what you need to do is rebase. It's quite painless if you haven't edited the same parts of the same files in both places.

And, I don't think we need `rlaplace`?

**Comment by bhaller** [comment]
> You're right - what you need to do is rebase. It's quite painless if you haven't edited the same parts of the same files in both places.

So @petrelharp, can I as the owner of the SLiM repo but *not* the owner of this PR, somehow do a merge-with-rebase?  Do I have any control over that?  Or do I have to ask the owner of the PR to please rebase their PR?  The problem is that somebody writes a PR, and then by the time I'm ready to merge that PR in, other changes have happened in the repo, which makes a merge commit that I dislike.  I want to merge the PR in using rebase; but it seems like I have to hassle the PR owner to do that for me, which seems weird.  Is there a better workflow?

> And, I don't think we need `rlaplace`?

OK, great.

**Comment by petrelharp** [comment]
In my experience, yes - you can push directly to a branch on someone else's fork of your repo (at least when it's been made a PR to your repo). So, you could rebase it for them. It's easier on you just to ask them to rebase it. But maybe the easiest way for you to do it is to do it all "locally" and leave their PR alone - so, checkout their branch locally, then rebase it, merge the resulting commit in, and just close the PR without merging it. That'll get the commit into git history just fine.

**Comment by bhaller** [comment]
Huh, ok.  Maybe the next time this comes up I'll see if you're free to show me how to do all this.  :->

**Pull request closed without merging**
