### PR TITLE
thrash about with CI until I debug #334

### PR DESCRIPTION
**Pull request by petrelharp**

### CODE REVIEW

**Comment by petrelharp** [comment]
Well, this just passed the tests, oddly.

**Comment by petrelharp** [comment]
OK, to get the error to occur here, I ssh in and then do:
```
source ~/.profile
set +e
set +o pipefail
export PATH=$PWD/Release:$PATH
cd treerec/tests
python3 -- -m pytest test_consistency.py::TestWithMutations::test_ts_slim_consistency\[test_____sexual_nonwf.slim\]
```
but then I can't get the segfault to occur in a debugger! I've done this a lot of times, no errors!
```
lldb /usr/local/miniconda/envs/anaconda-client-env/bin/python3 -- -m pytest test_consistency.py::TestWithMutations::test_ts_slim_consistency\[test_____sexual_nonwf.slim\]
```

**Comment by bhaller** [comment]
> ...but then I can't get the segfault to occur in a debugger! I've done this a lot of times, no errors!

Ah, always a joy when you get a bug that disappears when you're under the debugger.  :-O  That is probably because running under the debugger changes the layout of memory in some way, or switches to a different version of the standard library (different implementation of malloc, for example), or something like that.

Inserting print statements at strategic points is one strategy then.  You know the line of the test script that triggers the crash; so go inside the code that that line calls, and put print statements all over the place so you can see how far it gets before the crash occurs; that will let you pinpoint the area where the crash is happening.  Then add more print statements inside/before that area to examine all the relevant values.  Figure out what exactly is triggering the segfault – presumably a pointer to a bad address – and then trace backwards from there to find where the bad address comes from.  It can be a nightmare.  :-<

Another strategy, perhaps easier to pursue but it might or might not lead you to the bug, is to run the test, in the specific conditions where it segfaults, under Valgrind.  If you're lucky, Valgrind will lead you right to the specific spot where an uninitialized value is first used.  But if the error is more of a logic error than an undefined behavior error, Valgrind might not tell you very much.  It might still show you the specific line of code where the segfault happens.

**Comment by petrelharp** [comment]
I figured out how to get the bug in a debugger; see https://github.com/tskit-dev/tskit/issues/2429

**Comment by petrelharp** [comment]
Resolved!

**Pull request closed without merging**
