### PR TITLE
use new pyslim in CI tests

### PR DESCRIPTION
**Pull request by petrelharp**
I'll try to get those tests passing here...

### CODE REVIEW

**Comment by petrelharp** [comment]
holy cow the ubuntu tests are passing!

**Comment by petrelharp** [comment]
woah I did it
Screenshot from 2022-06-02 23-35-23

**Comment by petrelharp** [comment]
Ok! Tests are passing! I think you can merge this in and we're ready to go!

**Comment by bhaller** [comment]
Awesome!  I have no idea how people (i.e., you) figure out this kind of thing!

**Comment by petrelharp** [comment]
trial and error...

**Pull request merged**
