### PR TITLE
update python recipes; closes #285

### LINKED ISSUE #285: need to modernize pyslim-related APIs in recipes
Recipe 17.10 produces several deprecation warnings; replacement code is needed.  Also, apparently the use of `pyslim.load()` should be switched to `tskit.load()`, maybe just in 17.10, maybe throughout?  Everything seems to run OK for now, apart from warnings, so this is being pended to after 3.7.1 due to schedule pressure.  Clarification on the needed changes would be helpful @petrelharp.  Thanks!

### PR DESCRIPTION
**Pull request by petrelharp**
I think this brings all these up to date.

### CODE REVIEW

**Comment by petrelharp** [comment]
Failing only due to windows/python hell (purgatory?), it seems.

**Comment by bhaller** [comment]
I guess you only know whether it's hell or purgatory in hindsight, right?  If you ever escape from it, then it turns out it was purgatory.  :->

**Comment by petrelharp** [comment]
... and if you're never sure if you've *actually* escaped or if it's just an temporary illusion?

**Comment by bhaller** [comment]
So... maybe it's really just always hell.  ;->

**Comment by bhaller** [comment]
This looks good, thanks @petrelharp!

**Pull request merged**
