### PR TITLE
add debug loop to validate parent/child values

### PR DESCRIPTION
**Pull request by molpopgen**
I don't expect this to be merged.  The goal is to trigger what I believe to be a bug related to tskit-dev/tskit#402

### CODE REVIEW

**Comment by bhaller** [comment]
OK.  Let me know if/when there's something you want me to do.  :->

**Comment by molpopgen** [comment]
> OK. Let me know if/when there's something you want me to do. :->

Well, presumably first close the issue at `tskit`, as it is here not there?  After that, it is up to you, but perhaps implement a guard against allowing this many nodes to be recorded w/o simplifying?

**Comment by bhaller** [comment]
Sorry, I'm confused.  What bug are you referring to?  All I see is a pull request that you say you don't want to be merged.

**Comment by molpopgen** [comment]
See the issues linked to this PR.  I'm also assuming you saw the follow-up posts to tskit-dev/tskit#402, which is also linked to above.

**Comment by molpopgen** [comment]
If you aren't viewing on GitHub, then see #62, which is auto-linked to this PR via the GitHub interface.

**Comment by bhaller** [comment]
Ah, this makes more sense now.  I got an email about a new issue, but when I tried to look at it GitHub gave me an error page, so I thought that issue had been deleted, so then I wasn't sure what was going on.  Sorry, I'm not used to collaborating on GitHub.  :->

**Comment by molpopgen** [comment]
> Ah, this makes more sense now. I got an email about a new issue, but when I tried to look at it GitHub gave me an error page, so I thought that issue had been deleted, so then I wasn't sure what was going on. Sorry, I'm not used to collaborating on GitHub. :->

no prob!  GH has been on the fritz today--I had a similar thing happen w/another repo I was browsing.

**Comment by bhaller** [comment]
#62 is fixed, so this PR is no longer needed.  Thanks @molpopgen, good bug!

**Pull request closed without merging**
