### PR TITLE
exploratory looking at windows tests

### PR DESCRIPTION
**Pull request by petrelharp**
Not to be merged (yet?); looking at #277.

### CODE REVIEW

**Comment by petrelharp** [comment]
I have no idea why this is not working - I can pip install packages that are then not found, and conda install packages that are then not found.

**Comment by petrelharp** [comment]
Oh. Looks like I just had to clear the conda cache. And it failed *this* time because of #269.

**Comment by bhaller** [comment]
> I have no idea why this is not working - I can pip install packages that are then not found, and conda install packages that are then not found.

Probably it's a different issue, but someone in the Messer Lab just had a very similar problem, which was resolved by these comments:

> type pip3 to see what pip you were using, if it’s not the one in your environment it won’t install to your environment
> type python to see what Python you were using, if it’s not the one in your environment it won’t have pyslim even if pip installed it correctly to the environment
> your env is named py2.7 which implies its default python is Python 2, and pip3 installs packages for Python 3 (it’s in the name, pip3), so even if both of those programs are the right ones from your environment, you won’t be able to find a pip3-installed pyslim from a Python 2 shell
> 
> General tip is to not use Python 2 anymore. It’s discontinued and no one supports it anymore. For some years it existed alongside Python 3, and that generated a lot of confusion. But that time is gone, Python 2 has been fully officially phased out since 2019 I think.
> 
> It’s simple if your defaults are all consistently Python 3, as they should be in any new environment you make:
> conda create -n myenv python=3
> conda activate myenv
> # now both "pip" and "python" should default to the env's Python 3 installation
> pip install pyslim
> Then open python and import pyslim and you should be good.

I imagine you already know all that, but your problem sounds so similar that I thought I ought to mention it.

**Comment by bhaller** [comment]
Sorry about #269, I'll get on that.

**Comment by petrelharp** [comment]
Holy crap, I got this to work! Let me rebase and see if it still works.

**Comment by bhaller** [comment]
> Holy crap, I got this to work! Let me rebase and see if it still works.

Do you understand why it didn't work and now it does?  :->

**Comment by petrelharp** [comment]
> Do you understand why it didn't work and now it does? :->

Yes, I think so - by installing all the prerequisites on Windows using conda, not pip, and bumping the conda cache.

Although now I see it's failing again with the same error, wtf. Um, maybe I'll bump the cache again?

**Comment by petrelharp** [comment]
I think we're good to merge this!

**Pull request merged**
