### PR TITLE
Tskit C_1.0 beta

### LINKED ISSUE #304: Shift from tsk_vargen to tsk_variant
The tskit APIs for finding variants at sites is shifting; see https://github.com/tskit-dev/tskit/issues/2175.  We should respond to that shift the next time we update the tskit code in SLiM.  We might not get any compiler warning or error, since they plan to keep the old APIs present but undocumented for now, so I'm opening this issue as a reminder.  @petrelharp tagging you so this is on your radar too.  :->

### PR DESCRIPTION
**Pull request by petrelharp**
So far, it builds! I've done no tests yet. I've also removed vargen, so this closes #304 also.

### CODE REVIEW

**Comment by bhaller** [comment]
Awesome!  It still looks above like it is incorporating a whole bunch of commits on the multispecies branch that I did over the past months.  Does it need to be rebased or something?  "Files changed" shows as "542"!  :->  But that's awesome that it builds – progress!  Let me know if you need anything from my end.  Thanks!

**Comment by bhaller** [comment]
> ...(But that's awesome that it builds – progress!)

I see now that your "it builds" comment was from 5 days ago; I don't think I saw a notification about this PR until now, odd.  Anyhow, good stuff.  :->

**Comment by petrelharp** [comment]
Yeah, I messed up git there for a bit (I rebased against master instead of multispecies...). Fixed now. And - it *passes all the treerec tests* with my curent pyslim branch over at https://github.com/tskit-dev/pyslim/pull/253 ! I've got a fair bit of work still over there to get things passing, but this is probably all good (maybe some pyslim code changes to the test suite?).

**Comment by bhaller** [comment]
> Yeah, I messed up git there for a bit (I rebased against master instead of multispecies...). Fixed now. And - it _passes all the treerec tests_ with my curent pyslim branch over at [tskit-dev/pyslim#253](https://github.com/tskit-dev/pyslim/pull/253) ! I've got a fair bit of work still over there to get things passing, but this is probably all good (maybe some pyslim code changes to the test suite?).

Awesome!  Let me know when it's ready to approve.  Great to have this coming together; SLiM 4 beta 1 feels like it is close now.

**Pull request merged**
